/** Textos en inglés (clave: el texto original en español). Lo mantiene herramientas/textos.py. */
window.MR = window.MR || {};
MR.TEXTOS_EN = {
 "MIDNIGHT RINSE": "MIDNIGHT RINSE",
 "Idioma · Language": "Idioma · Language",
 "Normal": "Normal",
 "https://music.youtube.com/…": "https://music.youtube.com/…",
 "W": "W",
 "A": "A",
 "S": "S",
 "D": "D",
 "o": "or",
 "E": "E",
 "B": "B",
 "C": "C",
 "F": "F",
 "J": "J",
 "H": "H",
 "Esc": "Esc",
 "X": "X",
 "Start": "Start",
 "View / Select": "View / Select",
 "Paranoia": "Paranoia",
 "Pelusa": "Pelusa",
 "Midnight Rinse": "Midnight Rinse",
 "Midnight Rinse · Turno de Medianoche": "Midnight Rinse · Midnight Shift",
 "Gira el teléfono a horizontal": "Rotate your phone to landscape",
 "Turno de Medianoche": "Midnight Shift",
 "Continuar turno": "Continue shift",
 "Comenzar turno": "Start shift",
 "Guía de controles": "Controls guide",
 "Reiniciar todo": "Reset everything",
 "Instalar la app": "Install the app",
 "Para instalarlo en el iPhone: toca <b>Compartir</b> y luego <b>Agregar a pantalla de inicio</b>. Se abre a pantalla completa y funciona sin internet.": "To install on iPhone: tap <b>Share</b> and then <b>Add to Home Screen</b>. It opens full screen and works offline.",
 "Opciones": "Options",
 "Dificultad": "Difficulty",
 "Paseo: sin él ni sustos, solo explorar": "Stroll: no him, no scares, just exploring",
 "Tranquilo: menos sustos, más consumibles": "Calm: fewer scares, more consumables",
 "Pesadilla: sustos seguidos, casi nada que fumar": "Nightmare: back-to-back scares, almost nothing to smoke",
 "Subtítulos": "Subtitles",
 "Voces sintetizadas (las del navegador)": "Synthesized voices (the browser's)",
 "Reducir destellos de luz": "Reduce flashing lights",
 "Mostrar punto de mira": "Show crosshair",
 "Capa meta: usar la hora real de tu computadora": "Meta layer: use your computer's real time",
 "Vibración (perillas, monedas, trapeador, pasos)": "Vibration (knobs, coins, mop, footsteps)",
 "Micro-balanceo con el giroscopio": "Micro-sway with the gyroscope",
 "Ahorro de batería (30 FPS, como la PS1)": "Battery saver (30 FPS, like the PS1)",
 "Filtro de televisor viejo (CRT)": "Old TV filter (CRT)",
 "Sensibilidad de la mirada": "Look sensitivity",
 "Campo de visión": "Field of view",
 "Invertir el eje vertical al mirar": "Invert vertical axis when looking",
 "Tamaño de los subtítulos": "Subtitle size",
 "Grande": "Large",
 "Enorme": "Huge",
 "Volumen": "Volume",
 "Tu nombre en los susurros (opcional)": "Your name in the whispers (optional)",
 "vacío = sin nombre": "blank = no name",
 "Si escribes un nombre, algunos susurros lo dirán. Es opcional y no sale de tu navegador.": "If you enter a name, some whispers will say it. It's optional and doesn't leave your browser.",
 "Borrar registro del turno": "Clear shift log",
 "Tu música dentro del juego (YouTube Music u otra)": "Your in-game music (YouTube Music or other)",
 "<b>En la tele de la lavandería (celular y computadora).</b> En YouTube Music toca <b>Compartir → Copiar enlace</b> en una canción, un álbum o una playlist, y pégalo aquí. Sonará en la tele colgada entre las lavadoras y las secadoras: más fuerte si te acercas. Tócala para pausar y toca su perilla para cambiar de canción.": "<b>On the laundromat TV (phone and computer).</b> On YouTube Music, tap <b>Share → Copy link</b> on a song, an album, or a playlist, and paste it here. It'll play on the TV hanging between the washers and dryers: louder if you get closer. Tap it to pause and tap its knob to change songs.",
 "Poner en la tele": "Play on TV",
 "O por la radio del mostrador (99.9 FM):": "Or through the radio on the counter (99.9 FM):",
 "1) Abre YouTube Music y pon lo que quieras. 2) Pulsa «Conectar pestaña», elige la pestaña de YouTube Music y marca «Compartir audio de la pestaña». Tu música sonará desde la radio del mostrador, en la 99.9 FM, en 3D: más fuerte cerca, de lado si giras la cabeza, ahogada cuando él está cerca.": "1) Open YouTube Music and play whatever you want. 2) Click “Connect tab”, choose the YouTube Music tab, and check “Share tab audio”. Your music will play from the radio on the counter, on 99.9 FM, in 3D: louder up close, from the side if you turn your head, muffled when he's close.",
 "Elige canciones guardadas en tu teléfono y sonarán desde la radio del mostrador. O, si tienes YouTube Music Premium o Spotify, deja tu música sonando en su app y activa «Callar la radio del juego».": "Choose songs saved on your phone and they'll play from the radio on the counter. Or, if you have YouTube Music Premium or Spotify, leave your music playing in its app and turn on “Mute in-game radio”.",
 "Abrir YouTube Music": "Open YouTube Music",
 "Conectar pestaña": "Connect tab",
 "O elige canciones de tu dispositivo": "Or choose songs from your device",
 "Sonido de radio vieja (lo-fi)": "Old radio sound (lo-fi)",
 "Útil si tu música suena desde otra app": "Useful if your music is playing from another app",
 "Callar la radio del juego": "Mute in-game radio",
 "Sin conectar.": "Not connected.",
 "Desconectar": "Disconnect",
 "Archivo (<span id=\"archivo-cuenta\">0/0</span>)": "Archive (<span id=\"archivo-cuenta\">0/0</span>)",
 "Lo que has leído y escuchado. Toca una entrada para releerla.": "What you've read and heard. Tap an entry to re-read it.",
 "Objetos perdidos (<span id=\"objetos-cuenta\">0/0</span>)": "Lost and found (<span id=\"objetos-cuenta\">0/0</span>)",
 "Logros (<span id=\"logros-cuenta\">0/0</span>)": "Achievements (<span id=\"logros-cuenta\">0/0</span>)",
 "<span class=\"tecla\">W</span><span class=\"tecla\">A</span><span class=\"tecla\">S</span><span class=\"tecla\">D</span> caminar · <span class=\"tecla ancha\">ratón</span> mirar · <span class=\"tecla ancha\">clic</span> usar · <span class=\"tecla\">H</span> guía de controles · <span class=\"tecla\">Esc</span> pausa": "<span class=\"tecla\">W</span><span class=\"tecla\">A</span><span class=\"tecla\">S</span><span class=\"tecla\">D</span> walk · <span class=\"tecla ancha\">mouse</span> look · <span class=\"tecla ancha\">click</span> use · <span class=\"tecla\">H</span> controls guide · <span class=\"tecla\">Esc</span> pause",
 "Pulgar izquierdo: caminar · pulgar derecho: mirar · toca los objetos · <b>tres dedos</b>: pausa y guía. Juega en horizontal.": "Left thumb: walk · right thumb: look · tap objects · <b>three fingers</b>: pause and guide. Play in landscape.",
 "+18 · Terror psicológico, luces que parpadean y sonidos graves. Contiene consumo de tabaco, alcohol y cannabis (ficción). El registro del turno persiste entre partidas.": "+18 · Psychological horror, flashing lights, and low sounds. Contains tobacco, alcohol, and cannabis use (fiction). The shift log persists between playthroughs.",
 "Pausa": "Pause",
 "Continuar": "Continue",
 "Salir al bosque": "Go out to the forest",
 "Abandonar el turno": "Abandon the shift",
 "¿Reiniciar todo?": "Reset everything?",
 "El juego vuelve a empezar desde cero, como la primera vez:": "The game starts over from scratch, like the first time:",
 "Se borra el <b>registro del turno</b> (lo que la hoja recuerda de noches anteriores).": "The <b>shift log</b> is cleared (what the page remembers from previous nights).",
 "Tus <b>opciones</b> vuelven a como venían: volumen, subtítulos, sensibilidad, vibración y tu nombre.": "Your <b>options</b> reset to default: volume, subtitles, sensitivity, vibration, and your name.",
 "Se olvida el <b>enlace de tu música</b> y se desconecta lo que esté sonando.": "The <b>music link</b> is forgotten and whatever is playing is disconnected.",
 "El turno en curso se pierde.": "The current shift is lost.",
 "Sí, reiniciar todo": "Yes, reset everything",
 "Cancelar": "Cancel",
 "Teclado y ratón": "Keyboard and mouse",
 "Celular (gestos)": "Phone (gestures)",
 "Control (mando)": "Controller",
 "Moverte": "Move",
 "Caminar": "Walk",
 "ratón": "mouse",
 "Mirar alrededor": "Look around",
 "Usar las cosas (apunta al centro de la vista)": "Use things (aim at center of view)",
 "clic": "click",
 "Usar: monedas, ranura, puertas, la hoja, el teléfono, el trapeador": "Use: coins, coin slot, doors, the page, the phone, the mop",
 "<span class=\"tecla ancha\">clic</span> en la tablilla del mostrador": "<span class=\"tecla ancha\">click</span> on the clipboard on the counter",
 "Ver las tareas del turno <span class=\"g-nota\">(charcos, lavadoras, filtros, la hora)</span>": "View shift tasks <span class=\"g-nota\">(puddles, washers, filters, the time)</span>",
 "mantener clic": "hold click",
 "ratón ↔": "mouse ↔",
 "Girar perillas: lavadoras y radio": "Turn knobs: washers and radio",
 "Fregar un charco (con el trapeador) o limpiar un filtro de pelusa": "Mop a puddle (with the mop) or clean a lint filter",
 "<span class=\"tecla ancha\">clic</span> en el gato": "<span class=\"tecla ancha\">click</span> on the cat",
 "Acariciar a Pelusa <span class=\"g-nota\">(si bufa, él está cerca)</span>": "Pet Pelusa <span class=\"g-nota\">(if it hisses, he's close)</span>",
 "Tu cuerpo": "Your body",
 "mantener": "hold",
 "Limpiar el vaho de los lentes": "Wipe the fog off your glasses",
 "Cerrar los ojos <span class=\"g-nota\">(lo que no ves puede moverse)</span>": "Close your eyes <span class=\"g-nota\">(what you don't see can move)</span>",
 "Consumibles": "Consumables",
 "Cigarro <span class=\"g-nota\">(calma poco a poco; el humo empaña)</span>": "Cigarette <span class=\"g-nota\">(calms you bit by bit; the smoke fogs your glasses)</span>",
 "Petaca <span class=\"g-nota\">(necesitas la mano libre; marea y parpadeas más)</span>": "Flask <span class=\"g-nota\">(you need a free hand; makes you dizzy and you blink more)</span>",
 "Porro <span class=\"g-nota\">(el tiempo se estira… y llega la paranoia)</span>": "Joint <span class=\"g-nota\">(time stretches… and the paranoia sets in)</span>",
 "<span class=\"tecla ancha\">clic</span> en la máquina de café": "<span class=\"tecla ancha\">click</span> on the coffee machine",
 "Café por una moneda <span class=\"g-nota\">(parpadeas menos un rato)</span>": "Coffee for a coin <span class=\"g-nota\">(you blink less for a while)</span>",
 "Tu música": "Your music",
 "<span class=\"tecla ancha\">clic</span> en la tele": "<span class=\"tecla ancha\">click</span> on the TV",
 "Pausar o reanudar tu música": "Pause or resume your music",
 "<span class=\"tecla ancha\">clic</span> en su perilla": "<span class=\"tecla ancha\">click</span> on its knob",
 "Siguiente canción": "Next song",
 "perilla de la radio": "radio knob",
 "<b>94.1</b> el locutor · <b>99.9</b> tu música": "<b>94.1</b> the host · <b>99.9</b> your music",
 "El pasillo de servicio": "The service corridor",
 "<span class=\"tecla ancha\">clic</span> en la puerta trasera": "<span class=\"tecla ancha\">click</span> on the back door",
 "Entrar al pasillo <span class=\"g-nota\">(se abre a las 03:00)</span>": "Enter the corridor <span class=\"g-nota\">(opens at 03:00)</span>",
 "<span class=\"tecla ancha\">clic</span> en un casillero o en los fusibles": "<span class=\"tecla ancha\">click</span> on a locker or on the fuses",
 "Abrirlo · restablecerlos (los apagones duran la mitad)": "Open it · reset them (blackouts last half as long)",
 "El bosque": "The forest",
 "<span class=\"tecla ancha\">clic</span> en la puerta de vidrio": "<span class=\"tecla ancha\">click</span> on the glass door",
 "Salir al bosque <span class=\"g-nota\">(o en la pausa: «Salir al bosque»)</span>": "Go out to the forest <span class=\"g-nota\">(or from the pause menu: “Go out to the forest”)</span>",
 "<span class=\"tecla ancha\">clic</span> en la puerta de la fachada": "<span class=\"tecla ancha\">click</span> on the storefront door",
 "Volver a la lavandería": "Return to the laundromat",
 "<span class=\"tecla ancha\">clic</span> en una hoja mojada": "<span class=\"tecla ancha\">click</span> on a wet page",
 "Leerla y guardarla <span class=\"g-nota\">(hay seis… y la lavadora del claro las espera)</span>": "Read and keep it <span class=\"g-nota\">(there are six… and the washer in the clearing is waiting for them)</span>",
 "Secar la lluvia de los lentes <span class=\"g-nota\">(afuera se mojan)</span>": "Wipe the rain off your glasses <span class=\"g-nota\">(they get wet outside)</span>",
 "Hablar y menú": "Talk and menu",
 "Responder cuando alguien te habla": "Answer when someone speaks to you",
 "Abrir esta guía en cualquier momento": "Open this guide at any time",
 "Pausa: soltar el ratón, cambiar la música y abrir esta guía": "Pause: release the mouse, change the music, and open this guide",
 "No hay botones en pantalla: todo se hace con gestos. Juega con el teléfono en horizontal.": "There are no buttons on screen: everything is done with gestures. Play with your phone in landscape.",
 "Esquema de la pantalla: mitad izquierda para caminar, mitad derecha para mirar, esquina inferior derecha para los consumibles": "Screen layout: left half to walk, right half to look, bottom-right corner for consumables",
 "CAMINAR": "WALK",
 "apoya el pulgar y arrastra": "place your thumb and drag",
 "MIRAR": "LOOK",
 "arrastra · toca objetos": "drag · tap objects",
 "consumibles →": "consumables →",
 "<span class=\"gesto\">pulgar izq.</span> arrastrar": "<span class=\"gesto\">left thumb</span> drag",
 "Caminar <span class=\"g-nota\">(joystick invisible: donde apoyas el dedo queda el centro)</span>": "Walk <span class=\"g-nota\">(invisible joystick: wherever you place your finger becomes the center)</span>",
 "<span class=\"gesto\">pulgar der.</span> arrastrar": "<span class=\"gesto\">right thumb</span> drag",
 "📱 inclinar": "📱 tilt",
 "Balanceo suave de la mirada <span class=\"g-nota\">(giroscopio, opcional)</span>": "Gentle look sway <span class=\"g-nota\">(gyroscope, optional)</span>",
 "Usar las cosas": "Use things",
 "<span class=\"gesto\">☝ tocar</span> un objeto": "<span class=\"gesto\">☝ tap</span> an object",
 "Usar ESE objeto: monedas, ranura, manija, la hoja, el teléfono, el trapeador": "Use THAT object: coins, coin slot, handle, the page, the phone, the mop",
 "<span class=\"gesto\">☝ mantener</span> + arrastrar": "<span class=\"gesto\">☝ hold</span> + drag",
 "Girar una perilla; fregar un charco; limpiar un filtro": "Turn a knob; mop a puddle; clean a filter",
 "<span class=\"gesto\">☝ toque rápido</span> en perilla": "<span class=\"gesto\">☝ quick tap</span> on knob",
 "Avanzar un retén (un clic)": "Advance one notch (one click)",
 "<span class=\"gesto\">☝ tocar</span> al gato": "<span class=\"gesto\">☝ tap</span> the cat",
 "☝☝ doble toque": "☝☝ double tap",
 "Parpadear": "Blink",
 "✌ dos dedos ↓": "✌ two fingers ↓",
 "Limpiar el vaho de los lentes, justo donde frotas": "Wipe the fog off your glasses, right where you rub",
 "Consumibles (esquina inferior derecha)": "Consumables (bottom-right corner)",
 "desliza ↑": "swipe ↑",
 "Cigarro": "Cigarette",
 "desliza ←": "swipe ←",
 "Porro": "Joint",
 "desliza ↖": "swipe ↖",
 "Petaca <span class=\"g-nota\">(suelta antes el trapeador)</span>": "Flask <span class=\"g-nota\">(drop the mop first)</span>",
 "<span class=\"gesto\">☝ tocar</span> la tele": "<span class=\"gesto\">☝ tap</span> the TV",
 "Pausar o reanudar": "Pause or resume",
 "<span class=\"gesto\">☝ tocar</span> su perilla": "<span class=\"gesto\">☝ tap</span> its knob",
 "<span class=\"gesto\">☝ tocar</span> la puerta trasera": "<span class=\"gesto\">☝ tap</span> the back door",
 "<span class=\"gesto\">☝ tocar</span> un casillero o los fusibles": "<span class=\"gesto\">☝ tap</span> a locker or the fuses",
 "Abrirlo · restablecerlos": "Open it · reset them",
 "<span class=\"gesto\">☝ tocar</span> la puerta de vidrio": "<span class=\"gesto\">☝ tap</span> the glass door",
 "<span class=\"gesto\">☝ tocar</span> la puerta de la fachada": "<span class=\"gesto\">☝ tap</span> the storefront door",
 "<span class=\"gesto\">☝ tocar</span> una hoja mojada": "<span class=\"gesto\">☝ tap</span> a wet page",
 "Leerla y guardarla <span class=\"g-nota\">(hay seis)</span>": "Read and keep it <span class=\"g-nota\">(there are six)</span>",
 "Secar la lluvia de los lentes": "Wipe the rain off your glasses",
 "<span class=\"gesto\">☝ tocar</span> una respuesta": "<span class=\"gesto\">☝ tap</span> a response",
 "Responder": "Respond",
 "🖐 tres dedos": "🖐 three fingers",
 "Pausa: cambiar la música y abrir esta guía": "Pause: change the music and open this guide",
 "Funciona con controles de Xbox, PlayStation, Switch Pro y genéricos. Conéctalo y presiona cualquier botón. Vibra con los mismos golpes que el celular.": "Works with Xbox, PlayStation, Switch Pro, and generic controllers. Plug it in and press any button. Vibrates with the same pulses as the phone.",
 "stick izquierdo": "left stick",
 "stick derecho": "right stick",
 "Mirar": "Look",
 "Usar lo que miras": "Use what you're looking at",
 "stick der. ↔": "right stick ↔",
 "Girar perillas; fregar; limpiar filtros": "Turn knobs; mop; clean filters",
 "stick der.": "right stick",
 "Limpiar los lentes": "Clean glasses",
 "cruceta": "D-pad",
 "Cigarro · porro · petaca": "Cigarette · joint · flask",
 "Responder 1 · 2 · 3 cuando alguien te habla": "Answer 1 · 2 · 3 when someone talks to you",
 "Esta guía": "This guide",
 "En los menús": "In menus",
 "Cruceta o stick para moverte · <b>A</b> elegir · <b>B</b> volver · ◀ ▶ en los deslizadores": "D-pad or stick to move · <b>A</b> select · <b>B</b> back · ◀ ▶ on sliders",
 "Volver": "Back",
 "REGISTRO DE TURNO · LAVANDERÍA LA ESPUMA": "SHIFT LOG · LA ESPUMA LAUNDROMAT",
 "clic para dejar la hoja": "click to put down the page",
 "Control: ◀ 1 · ▲ 2 · ▶ 3 · ▼ 4": "Controller: ◀ 1 · ▲ 2 · ▶ 3 · ▼ 4",
 "Compartir resultado": "Share result",
 "Volver al inicio": "Back to start",
 "Hojas del registro": "Log pages",
 "Hoja {n} · ???": "Page {n} · ???",
 "Radio Nocturna 94.1": "Night Radio 94.1",
 "Noche {n} · ???": "Night {n} · ???",
 "RADIO NOCTURNA · 94.1 · NOCHE {n} · 02:40": "NIGHT RADIO · 94.1 · NIGHT {n} · 02:40",
 "(Afuera llueve. El bosque empieza donde se acaba la luz de la farola.)": "(It's raining outside. The forest begins where the streetlight's glow ends.)",
 "(Enciendes la linterna del celular.)": "(You turn on your phone's flashlight.)",
 "(Sales otra vez. La lavandería se queda sola a tus espaldas.)": "(You step outside again. The laundromat is left alone behind you.)",
 "(Vuelves a entrar. Huele a detergente y a tierra mojada.)": "(You go back inside. It smells like detergent and wet dirt.)",
 "(Hojas del registro: {n} de 6.)": "(Log pages: {n} of 6.)",
 "(Tienes las seis hojas. La lavadora del claro te espera.)": "(You have all six pages. The washer in the clearing is waiting for you.)",
 "(Abres la tapa. El uniforme deja de girar. Metes las seis hojas, una por una.)": "(You open the lid. The uniform stops spinning. You put in the six pages, one by one.)",
 "(La tapa no abre. Llevas {n} de 6 hojas del registro.)": "(The lid won't open. You have {n} of 6 log pages.)",
 "(Está tibia. Adentro gira ropa empapada… es un uniforme como el tuyo.)": "(It's warm. Soaked clothes spin inside… it's a uniform like yours.)",
 "(No está conectada a nada. Aun así, sigue lavando.)": "(It's not connected to anything. Even so, it keeps washing.)",
 "(En el vidrio de la puerta, tu reflejo tarda en parpadear.)": "(In the glass door, your reflection is slow to blink.)",
 "Inundación": "Flood",
 "Se reventó una tubería del pasillo de servicio. Va a haber más charcos de lo normal.": "A pipe burst in the service corridor. There will be more puddles than usual.",
 "Noche de apagones": "Blackout night",
 "La compañía de luz avisó de baja tensión. Si se apagan las luces, no salgas a revisar.": "The power company warned of low voltage. If the lights go out, don't go out to check.",
 "Niebla": "Fog",
 "Hay niebla. Los lentes se te van a empañar más; lleva un trapo.": "It's foggy. Your glasses will fog up more; bring a rag.",
 "Luna llena": "Full moon",
 "Por fin dejó de llover. Luna llena. Dicen que así se ve todo… también lo que no quieres ver.": "It finally stopped raining. Full moon. They say you can see everything like this… even what you don't want to see.",
 "¿Y el gato?": "Where's the cat?",
 "¿Has visto a Pelusa? No vino a comer.": "Have you seen Pelusa? It didn't come to eat.",
 "Paseo": "Stroll",
 "Tranquilo": "Calm",
 "Pesadilla": "Nightmare",
 "(Enciendes un porro. Huele a hierba y a ropa mojada.)": "(You light a joint. It smells like weed and wet clothes.)",
 "(La cajetilla está vacía.)": "(The pack is empty.)",
 "(Ya no te quedan porros.)": "(You don't have any joints left.)",
 "(Necesitas una moneda. El cambiador está junto a la entrada.)": "(You need a coin. The change machine is next to the entrance.)",
 "(La máquina zumba y escupe un vaso de cartón.)": "(The machine hums and spits out a paper cup.)",
 "(Necesitas la mano libre: suelta el trapeador.)": "(You need a free hand: put down the mop.)",
 "(La petaca está vacía.)": "(The flask is empty.)",
 "(Todo se vuelve más lento, más suave… y más cerca.)": "(Everything gets slower, softer… and closer.)",
 "(Apagas el cigarro contra el piso mojado.)": "(You stub out the cigarette against the wet floor.)",
 "(Todo se mece un poco. Parpadeas más de la cuenta.)": "(Everything sways a little. You blink more than you should.)",
 "(Un trago tibio. Te calma.)": "(A warm sip. It calms you.)",
 "(Café de máquina. Sabe a cartón, pero te despierta.)": "(Machine coffee. Tastes like cardboard, but it wakes you up.)",
 "01:10. Turno de noche en la Lavandería La Espuma.": "01:10. Night shift at La Espuma Laundromat.",
 "La hoja del registro está sobre el mostrador.": "The log page is on the counter.",
 "(Tres dedos: pausa y guía de controles.)": "(Three fingers: pause and controls guide.)",
 "(H: guía de controles · Esc: pausa.)": "(H: controls guide · Esc: pause.)",
 "(Nota del gerente en la tablilla: «{nota}»)": "(Manager's note on the clipboard: “{nota}”)",
 "Amaneció. Ya no vuelves… a menos que quieras.": "Dawn broke. You're not coming back… unless you want to.",
 "Amaneció. Pero esta noche vuelves.": "Dawn broke. But tonight you're coming back.",
 "[La impresora térmica imprime el registro del turno.]": "[The thermal printer prints the shift log.]",
 "[Radio: solo estática. En la 94.1 ya nadie habla.]": "[Radio: only static. Nobody is talking on 94.1 anymore.]",
 "[Radio: una voz entre la estática. No se entiende.]": "[Radio: a voice through the static. You can't make it out.]",
 "[Suena el teléfono público junto a la entrada.]": "[The payphone next to the entrance rings.]",
 "[La impresora vuelve a imprimir.] «{t}»": "[The printer prints again.] “{t}”",
 "Hace frío aquí dentro, ¿verdad? El agua de esas máquinas ya no se calienta.": "It's cold in here, isn't it? The water in those machines doesn't get hot anymore.",
 "(Sobre el mostrador, la hoja del registro cruje.)": "(On the counter, the log page rustles.)",
 "Disculpe... ¿qué hora es?": "Excuse me... what time is it?",
 "Son {hora}.": "It's {hora}.",
 "Faltan cinco minutos para las seis.": "It's five minutes to six.",
 "(No responder.)": "(Don't answer.)",
 "Son las cinco y trece. Ya terminó.": "It's five thirteen. It's over.",
 "Cliente: «{l}»": "Customer: “{l}”",
 "Cliente: ¿Qué hora es?": "Customer: What time is it?",
 "¿Qué hora es?": "What time is it?",
 "Tú: Son las cinco y trece. Ya terminó.": "You: It's five thirteen. It's over.",
 "…Entonces ya lo sabes.": "…Then you already know.",
 "(Se levanta despacio, camina hacia la puerta de vidrio y ya no está.)": "(He stands up slowly, walks toward the glass door, and is gone.)",
 "Tú: Faltan cinco minutos para las seis.": "You: It's five minutes to six.",
 "Gracias. Entonces todavía hay tiempo.": "Thank you. Then there's still time.",
 "Tú: Son {hora}.": "You: It's {hora}.",
 "No. No es esa hora.": "No. That's not the time.",
 "(No respondes. El cliente se queda mirando el reloj.)": "(You don't answer. The customer stares at the clock.)",
 "(Alguien está sentado en el banco amarillo. No lo oíste entrar.)": "(Someone is sitting on the yellow bench. You didn't hear him come in.)",
 "(susurros: «…{n}…»)": "(whispers: “…{n}…”)",
 "(susurros: «{w}»)": "(whispers: “{w}”)",
 "(Del otro lado solo se oye una lavadora girando. Luego, alguien cuelga.)": "(On the other end, all you hear is a washer spinning. Then, someone hangs up.)",
 "No lo mires a la cara. Si te pregunta la hora... faltan cinco minutos para las seis. Faltan cinco minutos para las seis.": "Don't look at his face. If he asks you the time... it's five minutes to six. It's five minutes to six.",
 "(El teléfono deja de sonar.)": "(The phone stops ringing.)",
 "(Pista: {t})": "(Hint: {t})",
 "la hoja del registro está sobre el mostrador. Tócala para leer las reglas.": "the log page is on the counter. Touch it to read the rules.",
 "pon a lavar. Saca monedas del cambiador junto a la entrada, mételas en la ranura y gira la perilla. Su ruido tapa el zumbido.": "start a wash. Get coins from the change machine next to the entrance, put them in the coin slot, and turn the knob. Its noise drowns out the hum.",
 "hay charcos en el pasillo y pronto revisan. El trapeador está en el almacén, al fondo a la izquierda.": "there are puddles in the aisle and an inspection is coming soon. The mop is in the storage room, in the back on the left.",
 "una secadora tiene el filtro lleno de pelusa. Mantén presionado sobre el filtro para limpiarlo.": "one dryer has a filter full of lint. Hold down on the filter to clean it.",
 "la tablilla del mostrador te dice qué falta.": "the clipboard on the counter tells you what's left.",
 "Son las {h}.": "It's {h}.",
 "Noche normal. Que siga así.": "Normal night. Keep it that way.",
 "Pasillo central: {n} charco": "Center aisle: {n} puddle",
 "Pasillo central: {n} charcos": "Center aisle: {n} puddles",
 "(revisión a las {h}; con 3 o más es falta).": "(inspection at {h}; 3 or more is a strike).",
 "(ya no hay más revisiones).": "(there are no more inspections).",
 "Lavadoras funcionando: {n} de 6 (con 3 o más, su ruido tapa el zumbido).": "Washers running: {n} of 6 (with 3 or more, their noise drowns out the hum).",
 "Filtros de pelusa: el más lleno, secadora {n} al {p} %.": "Lint filters: fullest, dryer {n} at {p} %.",
 "• No le mires la cara al cliente del banco.": "• Don't look at the face of the customer on the bench.",
 "• Si te pregunta la hora: «Faltan cinco minutos para las seis».": "• If he asks you the time: “It's five minutes to six”.",
 "• Si alguien te pregunta la hora, responde con cuidado.": "• If anyone asks you the time, answer carefully.",
 "• La puerta trasera quedó entreabierta.": "• The back door was left ajar.",
 "Los fusibles están allá.": "The fuses are over there.",
 "• Hojas del registro en el bosque: {n} de 6.": "• Log pages in the forest: {n} of 6.",
 "TAREAS DEL TURNO · TABLILLA DEL MOSTRADOR": "SHIFT TASKS · COUNTER CLIPBOARD",
 "Dificultad: {d} (faltas permitidas para el final bueno: {f})": "Difficulty: {d} (strikes allowed for the good ending: {f})",
 "Salidas al bosque: {n} · Hojas del registro: {h} de 6": "Trips to the forest: {n} · Log pages: {h} of 6",
 "Pasillo de servicio: {n} visita": "Service corridor: {n} visit",
 "Pasillo de servicio: {n} visitas": "Service corridor: {n} visits",
 "Fusibles: restablecidos": "Fuses: reset",
 "Fusibles: sin tocar": "Fuses: untouched",
 "Evaluación del turno: {nota} ({p} puntos)": "Shift review: {nota} ({p} points)",
 "05:12 · Paseo nocturno": "05:12 · Night stroll",
 "Recorriste la lavandería, el bosque y el pasillo sin que nadie te mirara. Afuera sigue lloviendo. Esta vez fue solo un paseo.": "You walked through the laundromat, the forest, and the corridor without anyone looking at you. Outside, it's still raining. This time was just a stroll.",
 "05:12 · Turno terminado": "05:12 · Shift ended",
 "Las lavadoras se detienen una por una. Afuera sigue lloviendo, pero la puerta por fin abre. El banco amarillo está vacío y seco.": "The washers stop one by one. Outside, it's still raining, but the door finally opens. The yellow bench is empty and dry.",
 "Él no volvió a preguntar la hora. Nadie volverá a preguntártela.": "He didn't ask the time again. No one will ever ask you again.",
 "01:10 · Turno de medianoche": "01:10 · Midnight shift",
 "Parpadeas. El reloj marca la una y diez. Sobre el mostrador, el registro dice: «{t}» El turno no terminó.": "You blink. The clock reads ten past one. On the counter, the shift log reads: “{t}” The shift didn't end.",
 "Empleado del mes. Tu foto ya está junto al cambiador. Nadie recuerda haberla tomado.": "Employee of the month. Your photo is already next to the change machine. No one remembers taking it.",
 "Buen turno. El pasillo brilla. Casi no se nota lo que pasó.": "Good shift. The aisle shines. You can barely tell what happened.",
 "Pasable. Hay pelusa en un filtro y alguien dejó huellas en el vidrio.": "Passable. There's lint in a filter and someone left prints on the glass.",
 "El gerente quiere hablar contigo. Mañana. A la una y diez.": "The manager wants to talk to you. Tomorrow. At ten past one.",
 "No vuelvas mañana… aunque siempre vuelves.": "Don't come back tomorrow… though you always come back.",
 "(Control conectado: {n}.)": "(Controller connected: {n}.)",
 "(Tienes las manos ocupadas con el trapeador.)": "(Your hands are full with the mop.)",
 "(Está cerrada con llave. Del otro lado, algo gotea.)": "(It's locked. On the other side, something is dripping.)",
 "(Necesitas el trapeador. Está en el almacén, al fondo a la izquierda.)": "(You need the mop. It's in the storage room, in the back on the left.)",
 "(Filtro limpio. La pelusa está tibia y húmeda.)": "(Filter clean. The lint is warm and damp.)",
 "(La perilla gira, pero la lavadora no arranca sin una moneda.)": "(The knob turns, but the washer won't start without a coin.)",
 "(Esta lavadora ya está en marcha.)": "(This washer is already running.)",
 "(Ya hay una moneda dentro. Gira la perilla.)": "(There's already a coin inside. Turn the knob.)",
 "(No tienes monedas. El cambiador está junto a la entrada.)": "(You don't have any coins. The change machine is next to the entrance.)",
 "(Ya hay monedas en la bandeja. Tómalas.)": "(There are already coins in the tray. Take them.)",
 "(Ya tienes los bolsillos llenos de monedas.)": "(Your pockets are already full of coins.)",
 "(La bandeja está vacía. Presiona el botón amarillo.)": "(The tray is empty. Press the yellow button.)",
 "(La puerta está trabada mientras lava.)": "(The door is locked while it's washing.)",
 "(Tono de marcar. Nadie del otro lado.)": "(Dial tone. No one on the other end.)",
 "(Huele a tela quemada. Una secadora está saturada de pelusa.)": "(Smells like burning fabric. A dryer is clogged with lint.)",
 "(Pelusa te ignora con mucha dignidad.)": "(Pelusa ignores you with great dignity.)",
 "(El gato ronronea. En su collar dice «Pelusa».)": "(The cat purrs. Its collar says “Pelusa”.)",
 "(Pelusa ronronea.)": "(Pelusa purrs.)",
 "Turno del 14 de octubre · R.": "Shift of October 14 · R.",
 "Salí a tirar la basura y el estacionamiento ya no existía. Hay pinos altísimos pegados al cristal de la entrada y el olor a lluvia no viene de la calle. Juro que cuando checamos tarjeta a la una todavía había pavimento.": "I went out to take out the trash and the parking lot no longer existed. There are towering pines pressed against the entrance glass, and the smell of rain isn't coming from the street. I swear there was still pavement when we clocked in at one.",
 "Turno del 22 de octubre · E.": "Shift of October 22 · E.",
 "Me escapé a fumar entre los árboles porque el zumbido del pasillo me estaba volviendo loco. En un claro encontré una lavadora blanca centrifugando sola, sin ningún cable. El tambor vibra caliente y huele a jabón fresco.": "I snuck out to smoke among the trees because the hum in the corridor was driving me crazy. In a clearing I found a white washer spinning alone, without any cords. The drum vibrates warm and smells like fresh soap.",
 "Turno del 29 de octubre · S.": "Shift of October 29 · S.",
 "El tipo del abrigo largo no solo se sienta en la banca amarilla. Lo vi parado detrás de un tronco grueso, mirándome fijo en la oscuridad. Cada vez que parpadeaba para enfocar la vista, aparecía dos metros más cerca.": "The guy in the long coat doesn't just sit on the yellow bench. I saw him standing behind a thick trunk, staring right at me in the dark. Every time I blinked to focus my eyes, he appeared two meters closer.",
 "Turno del 6 de noviembre · D.": "Shift of November 6 · D.",
 "Me acerqué a la máquina del bosque con la linterna para ver qué tenía dentro. La ropa que da vueltas lleva mi gafete bordado y la misma mancha de cloro en la manga. No quise tocar el cristal: sentí frío en el pecho, como si estuviera empapado.": "I walked up to the machine in the forest with the flashlight to see what was inside. The clothes spinning inside have my embroidered name tag and the same bleach stain on the sleeve. I didn't want to touch the glass: I felt cold in my chest, as if I were soaked.",
 "Turno del 12 de noviembre · T.": "Shift of November 12 · T.",
 "El reloj no va a marcar las 05:12 jamás mientras estas hojas sigan regadas en el lodo. Cada turno fallido arrancó una página y alimentó la niebla de afuera. El local se queda con nuestras horas perdidas para no tener que apagar la luz nunca.": "The clock is never going to hit 05:12 as long as these pages stay scattered in the mud. Each failed shift tore out a page and fed the fog outside. The place keeps our lost hours so it never has to turn off the lights.",
 "Turno del 19 de noviembre · A.": "Shift of November 19 · A.",
 "Si encontraste las seis hojas del registro, llévalas a la lavadora entre los pinos antes de las 05:12. Abre la tapa y mételas todas con el uniforme que gira. Es la única forma de cortar el ciclo. No dejes que te vea hacerlo.": "If you found the six log pages, take them to the washer among the pines before 05:12. Open the lid and put them all in with the spinning uniform. It's the only way to break the cycle. Don't let him see you do it.",
 "Son las dos y cuarenta en Radio Nocturna, noventa y cuatro punto uno. Para quienes siguen despiertos: si esta noche alguien les pregunta la hora, respondan con cuidado.": "It's two forty on Night Radio, 94.1. For those still awake: if someone asks you the time tonight, answer carefully.",
 "Son las dos y cuarenta en Radio Nocturna. Saludos a quien nos sintoniza entre el olor a jabón y centrifugados. No dejes que se apaguen los tambores; el silencio trae visitas.": "It's two forty on Night Radio. Greetings to whoever is tuning in amid the smell of soap and spin cycles. Don't let the drums stop; silence brings visitors.",
 "Son las dos y cuarenta en Radio Nocturna, bajo esta lluvia interminable. Si miras por el cristal, verás que los árboles crecieron demasiado cerca. Mejor concéntrate en fregar el pasillo.": "It's two forty on Night Radio, under this endless rain. If you look through the glass, you'll see the trees have grown too close. Better focus on mopping the aisle.",
 "Son las dos y cuarenta aquí en Radio Nocturna. Me pregunto cuántos nombres caben en siete casilleros de metal oxidado. El tuyo ya estaba grabado antes de que llegaras, querido oyente.": "It's two forty here on Night Radio. I wonder how many names fit in seven rusty metal lockers. Yours was already engraved before you arrived, dear listener.",
 "Son las dos y cuarenta en Radio Nocturna. Dicen que en el claro del bosque una máquina sin cable sigue lavando tu ropa. No vayas a buscarla; el zumbido tiene hambre esta noche.": "It's two forty on Night Radio. They say that in the forest clearing, a machine with no cord is still washing your clothes. Don't go looking for it; the hum is hungry tonight.",
 "Son las dos y cuarenta en Radio Nocturna. Tu reloj siempre se rinde a las cinco y doce, pero la noche no termina ahí. Falta un minuto que nadie te pagará jamás.": "It's two forty on Night Radio. Your watch always gives up at five twelve, but the night doesn't end there. There's one minute that no one will ever pay you for.",
 "Son las dos y cuarenta en Radio Nocturna. Grábate bien este secreto: la hora verdadera son las cinco y trece. Si logras ver ese minuto en tu reloj, tal vez vuelvas a casa.": "It's two forty on Night Radio. Remember this secret well: the true time is five thirteen. If you manage to see that minute on your watch, maybe you'll make it home.",
 "Son las dos y cuarenta en Radio Nocturna, y esta es nuestra última transmisión para ti. Ya reconoces al hombre del abrigo, ¿verdad? Buen turno eterno, amigo; de aquí ya nadie sale.": "It's two forty on Night Radio, and this is our last broadcast for you. You recognize the man in the coat by now, don't you? Have a good eternal shift, friend; nobody gets out of here anymore.",
 "…no levantes la vista…": "…don't look up…",
 "…gira sin corriente…": "…it spins without power…",
 "…limpia el filtro rápido…": "…clean the filter fast…",
 "…el abrigo huele a tierra…": "…the coat smells like dirt…",
 "…no lo mires al rostro…": "…don't look at his face…",
 "…el agua viene turbia…": "…the water runs murky…",
 "…tapa el zumbido grave…": "…drown out the low hum…",
 "…los árboles tocan el vidrio…": "…the trees touch the glass…",
 "…pregunta siempre lo mismo…": "…he always asks the same thing…",
 "…tu nombre ya estaba ahí…": "…your name was already there…",
 "…cinco y doce para siempre…": "…five twelve forever…",
 "…la hora verdadera vendrá…": "…the true time will come…",
 "…cinco y trece no llega…": "…five thirteen never comes…",
 "…el banco amarillo está frío…": "…the yellow bench is cold…",
 "…siete ya se quedaron…": "…seven already stayed…",
 "…nadie vendrá a relevarte…": "…no one is coming to relieve you…",
 "05:13 · Fin del turno": "05:13 · End of shift",
 "Él ya no estaba para verlo. Metes las seis hojas en el tambor y la lavadora se detiene por primera vez. Cuando vuelves, la lavandería está a oscuras y el letrero dice CERRADO. Sobre el mostrador, el registro está en blanco. Afuera ya es de día. Por fin sales a la calle.": "He wasn't there to see it. You put the six pages into the drum and the washer stops for the first time. When you head back, the laundromat is dark and the sign says CLOSED. On the counter, the shift log is blank. Outside, it's daylight. You finally step out onto the street.",
 "Último ciclo de lavado": "Last wash cycle",
 "Metes las seis páginas empapadas en el tambor y la máquina traga la tinta disuelta con un crujido metálico. El zumbido grave se apaga de golpe junto con los pinos, devolviéndote al pavimento frío de la avenida. Tu reloj de pulsera por fin marca las 05:13.": "You put the six soaked pages into the drum and the machine swallows the dissolved ink with a metallic crunch. The low hum shuts off suddenly along with the pines, returning you to the cold pavement of the avenue. Your wristwatch finally reads 05:13.",
 "(La radio cambia sola de estación. Entre la estática: «…no lo mires a la cara…».)": "(The radio changes stations on its own. Through the static: “…don't look at his face…”.)",
 "Primer turno": "First shift",
 "Termina un turno, del modo que sea.": "Finish a shift, one way or another.",
 "Consigue que la puerta por fin abra.": "Get the door to finally open.",
 "La una y diez otra vez": "Ten past one again",
 "Que el turno no termine.": "Don't let the shift end.",
 "Último ciclo": "Last cycle",
 "Mete las seis hojas en la lavadora del claro.": "Put the six pages into the washer in the clearing.",
 "Fin del turno": "End of shift",
 "Dile la hora verdadera y cierra el ciclo en la misma noche.": "Tell him the true time and close the cycle in the same night.",
 "Aire fresco": "Fresh air",
 "Sal al bosque.": "Go out to the forest.",
 "Archivista": "Archivist",
 "Encuentra una hoja mojada del registro.": "Find a wet page from the shift log.",
 "Lo viste": "You saw him",
 "Un relámpago lo reveló entre los árboles.": "A flash of lightning revealed him among the trees.",
 "Canal propio": "Own channel",
 "Pon tu música en la tele de la lavandería.": "Play your music on the laundromat TV.",
 "Ten la radio sintonizada cuando habla el locutor.": "Have the radio tuned in when the host speaks.",
 "Ruido blanco": "White noise",
 "Ten las seis lavadoras funcionando a la vez.": "Have all six washers running at once.",
 "Pasillo impecable": "Spotless aisle",
 "Termina un turno sin faltas en el pasillo ni en los filtros.": "Finish a shift with no strikes in the aisle or filters.",
 "Ojos al suelo": "Eyes on the floor",
 "Termina un turno con él presente sin mirarlo nunca a la cara.": "Finish a shift with him present without ever looking at his face.",
 "Fuma los tres porros en un mismo turno.": "Smoke all three joints in a single shift.",
 "Acaricia al gato de la lavandería.": "Pet the laundromat cat.",
 "Turno de pesadilla": "Nightmare shift",
 "Consigue que la puerta abra en dificultad Pesadilla.": "Get the door to open on Nightmare difficulty.",
 "Electricista": "Electrician",
 "Restablece los fusibles del pasillo de servicio.": "Reset the fuses in the service corridor.",
 "Turno largo": "Long shift",
 "Tómate tres cafés de máquina en un mismo turno.": "Drink three coffees from the machine in a single shift.",
 "La hora verdadera": "The true time",
 "Dile la hora que nadie más sabe.": "Tell him the time that no one else knows.",
 "Detrás de ti": "Behind you",
 "Velo en el vidrio de una lavadora.": "See him in the glass of a washer.",
 "Objetos perdidos": "Lost and found",
 "Encuentra seis objetos olvidados en las lavadoras.": "Find six items left behind in the washers.",
 "Ya tenías casillero": "You already had a locker",
 "Abre el último casillero del pasillo.": "Open the last locker in the corridor.",
 "Un logro oculto.": "A hidden achievement.",
 "Este navegador no puede capturar pestañas. Usa Chrome o Edge en una computadora, o elige archivos.": "This browser cannot capture tabs. Use Chrome or Edge on a computer, or choose files.",
 "No llegó audio. Vuelve a intentarlo y marca «Compartir audio de la pestaña».": "No audio received. Try again and check “Share tab audio”.",
 "pestaña": "tab",
 "Conectado: tu pestaña suena en la radio del mostrador (99.9 FM).": "Connected: your tab is playing on the radio on the counter (99.9 FM).",
 "Captura cancelada.": "Capture canceled.",
 "No elegiste archivos de audio.": "You didn't select any audio files.",
 "Conectado: {n} canción en la radio del mostrador (99.9 FM).": "Connected: {n} song on the radio on the counter (99.9 FM).",
 "Conectado: {n} canciones en la radio del mostrador (99.9 FM).": "Connected: {n} songs on the radio on the counter (99.9 FM).",
 "Desconectado.": "Disconnected.",
 "Un calcetín de niño": "A child's sock",
 "Seco, aunque el ciclo acaba de terminar.": "Dry, even though the cycle just ended.",
 "Un anillo de matrimonio": "A wedding ring",
 "Grabado por dentro: «14·10». La misma fecha de la primera hoja del bosque.": "Engraved inside: “14·10”. The same date as the first page from the forest.",
 "Una moneda extranjera": "A foreign coin",
 "De ningún país que conozcas. Cabe justo en la ranura.": "From no country you know. Fits right into the coin slot.",
 "Un botón de abrigo": "A coat button",
 "Negro, enorme. Huele a tierra mojada.": "Black, huge. Smells like wet dirt.",
 "Un ticket de 1987": "A receipt from 1987",
 "Lavandería La Espuma. Turno de 01:10 a 05:12. La letra es la tuya.": "La Espuma Laundromat. Shift from 01:10 to 05:12. The handwriting is yours.",
 "Un reloj de pulsera": "A wristwatch",
 "Detenido a las 05:13. No tiene corona para darle cuerda.": "Stopped at 05:13. It has no crown to wind it.",
 "Un gafete desteñido": "A faded nametag",
 "Solo se lee la inicial: R. La foto está raspada.": "Only the initial can be read: R. The photo is scratched off.",
 "Una aguja de pino": "A pine needle",
 "En el centro del tambor. Ninguna ventana da al bosque.": "In the center of the drum. No windows face the forest.",
 "Una llave pequeña": "A small key",
 "Con una etiqueta: «casillero 7».": "With a tag: “locker 7”.",
 "Un diente de leche": "A baby tooth",
 "En una bolsita de plástico con tu nombre de niño.": "In a small plastic bag with your name as a child.",
 "Una foto instantánea": "An instant photo",
 "Tú, dormido en el banco amarillo. Tomada desde muy cerca.": "You, asleep on the yellow bench. Taken from very close.",
 "Una nota doblada": "A folded note",
 "Con letra apretada: «No te voy a dejar salir. Me gusta tu compañía».": "In cramped handwriting: “I'm not going to let you out. I like your company”.",
 "(Entre la ropa húmeda: {n}. {d})": "(Among the damp clothes: {n}. {d})",
 "(Ya tenías uno igual.)": "(You already had one just like it.)",
 "(noche {n})": "(night {n})",
 "Algún ciclo lo dejará.": "Some cycle will leave it behind.",
 "(Continúas el turno. Son las {h}.)": "(You continue the shift. It's {h}.)",
 "(Casillero de R. Un gafete con la foto raspada. Huele a cloro.)": "(R's locker. A nametag with the photo scratched off. Smells like bleach.)",
 "(Casillero de E. Una cajetilla vacía y un encendedor que ya no prende.)": "(E's locker. An empty pack and a lighter that won't light anymore.)",
 "(Casillero de S. Alguien escribió por dentro, con plumón: «parpadea menos».)": "(S's locker. Someone wrote inside with marker: “blink less”.)",
 "(Casillero de D. Una linterna sin pilas y una manga de uniforme, sola.)": "(D's locker. A flashlight without batteries and a uniform sleeve, alone.)",
 "(Casillero de T. Hojas de registro en blanco, todas con la misma hora: 05:12.)": "(T's locker. Blank log pages, all with the same time: 05:12.)",
 "(Casillero de A. Vacío. En el fondo hay lodo seco, como de bosque.)": "(A's locker. Empty. At the bottom is dried mud, like from the forest.)",
 "(El casillero tiene tu nombre. Adentro hay un gancho vacío, todavía tibio, y una etiqueta: «05:13».)": "(The locker has your name on it. Inside is an empty hanger, still warm, and a tag: “05:13”.)",
 "(Al fondo, junto a las secadoras, se oye un clic metálico. La puerta trasera quedó entreabierta.)": "(In the back, next to the dryers, a metallic click is heard. The back door was left ajar.)",
 "TÚ": "YOU",
 "(El pasillo de servicio huele a óxido y a jabón viejo. Algo gotea.)": "(The service corridor smells like rust and old soap. Something is dripping.)",
 "(Vuelves a la sala. Las secadoras siguen girando.)": "(You return to the main room. The dryers are still spinning.)",
 "(Los fusibles ya están restablecidos.)": "(The fuses are already reset.)",
 "(Bajas y subes los fusibles. Afuera, las luces de la lavandería dejan de zumbar un momento.)": "(You flip the fuses down and up. Outside, the laundromat lights stop buzzing for a moment.)",
 "Pega un enlace de YouTube Music o de YouTube.": "Paste a YouTube Music or YouTube link.",
 "Eso no parece un enlace.": "That doesn't look like a link.",
 "Solo funcionan enlaces de YouTube o YouTube Music.": "Only YouTube or YouTube Music links work.",
 "Ese es el enlace de una página. En YouTube Music abre el álbum o la playlist y usa Compartir → Copiar enlace (trae «list=»).": "That's a link to a page. In YouTube Music, open the album or playlist and use Share → Copy link (it includes “list=”).",
 "Tus «Me gusta» y «Ver más tarde» son privados y YouTube no los deja salir de su app. Haz una playlist pública o no listada y pega su enlace.": "Your “Liked videos” and “Watch Later” are private and YouTube won't let them leave its app. Make a public or unlisted playlist and paste its link.",
 "No encontré ninguna canción ni playlist en ese enlace.": "Couldn't find any songs or playlists at that link.",
 "sin conexión": "offline",
 "YouTube no funciona abriendo el archivo con doble clic: juega desde la página publicada (GitHub Pages).": "YouTube doesn't work by double-clicking the file: play from the published page (GitHub Pages).",
 "Conectando con YouTube…": "Connecting to YouTube…",
 "No se pudo cargar YouTube. ¿Hay internet?": "Couldn't load YouTube. Is there internet?",
 "Listo. Toca ▶ en el reproductor para que empiece a sonar.": "Ready. Press ▶ on the player to start playing.",
 "Sonando en la tele: «{t}».": "Now playing on the TV: “{t}”.",
 "Sonando en la tele.": "Now playing on the TV.",
 "En pausa: «{t}».": "Paused: “{t}”.",
 "En pausa.": "Paused.",
 "Esa canción no se deja reproducir fuera de YouTube (lo decide la disquera).": "That song can't be played outside of YouTube (the record label's decision).",
 "El enlace no es válido.": "The link is invalid.",
 "Tu navegador no pudo reproducir ese video.": "Your browser couldn't play that video.",
 "Ese video no existe o es privado.": "That video doesn't exist or is private.",
 "YouTube rechazó la conexión desde esta página.": "YouTube refused the connection from this page.",
 "YouTube dio un error ({c}).": "YouTube returned an error ({c}).",
 "{m} Paso a la siguiente…": "{m} Skipping to the next one…",
 "{m} Prueba otra versión de la canción (por ejemplo, la de «Audio» o «Letra»).": "{m} Try another version of the song (for example, “Audio” or “Lyrics”).",
 "(La tele solo da nieve. Pon tu música desde la pausa: «Tu música dentro del juego».)": "(The TV only shows static. Play your music from pause: “Your in-game music”.)",
 "(No hay luz.)": "(The power is out.)",
 "(Cambias de canal. Nieve en todos.)": "(You change the channel. Static on all of them.)",
 "LA ESPUMA · 24 H": "LA ESPUMA · 24 H",
 "textura desconocida:": "unknown texture:",
 "El registro guardado dice: «{t}»": "The saved shift log says: “{t}”",
 "El registro del turno está vacío.": "The shift log is empty.",
 "Son las {h}. Deberías estar durmiendo.": "It's {h}. You should be sleeping.",
 "Continuar turno ({h} · {d})": "Continue shift ({h} · {d})",
 "(hoja en blanco)": "(blank page)",
 "Saqué {nota} en Midnight Rinse ({dif}): «{titulo}».": "I got {nota} in Midnight Rinse ({dif}): “{titulo}”.",
 "Encontré {n} de 6 hojas en el bosque.": "I found {n} of 6 pages in the forest.",
 "¿Aguantas el turno de medianoche?": "Can you handle the midnight shift?",
 "Copiado. Pégalo donde quieras.": "Copied. Paste it wherever you want.",
 "en punto": "o'clock",
 "CAFÉ": "COFFEE",
 "Turno asignado sin incidencias. Recuerde fregar el pasillo central cada 45 minutos.": "Shift assigned without incident. Remember to mop the center aisle every 45 minutes.",
 "¿Por qué sigues limpiando si sabes que el agua nunca va a volver a ser clara?": "Why do you keep cleaning if you know the water will never be clear again?",
 "fase no válida:": "invalid phase:",
 "¿Tu navegador tiene WebGL activado?": "Does your browser have WebGL enabled?",
 "HOJA MOJADA DEL REGISTRO · {f}": "WET LOG PAGE · {f}",
 "Noche {n}": "Night {n}",
 "[Radio] {l}": "[Radio] {l}",
 "Cliente: {l}": "Customer: {l}",
 "[Teléfono] {l}": "[Phone] {l}",
 "Nota del gerente: {nota}": "Manager's note: {nota}",
 "Noche especial: {n}": "Special night: {n}",
 "Miradas a su cara después de la advertencia: {n}": "Looks at his face after the warning: {n}",
 "Revisiones del pasillo con charcos: {n} de {de}": "Aisle inspections with puddles: {n} of {de}",
 "Filtros de pelusa saturados: {n}": "Clogged lint filters: {n}",
 "Charcos fregados: {n}": "Puddles mopped: {n}",
 "Parpadeos: {n}": "Blinks: {n}",
 "Cigarros: {c} · Tragos de la petaca: {t} · Porros: {p} · Cafés: {k}": "Cigarettes: {c} · Sips from the flask: {t} · Joints: {p} · Coffees: {k}",
 "Caricias a Pelusa: {c} · Bufidos de alarma: {b} · Objetos perdidos encontrados: {o}": "Pets for Pelusa: {c} · Warning hisses: {b} · Lost items found: {o}",
 "★ Logro: {t}": "★ Achievement: {t}",
 "No se pudo capturar la pestaña: {e}": "Couldn't capture the tab: {e}",
 "Turno asignado. NO lo mires directamente a la cara. Si te pregunta la hora, dile que faltan cinco minutos para las seis.": "Shift assigned. DO NOT look him directly in the face. If he asks you the time, tell him it's five minutes to six.",
 "No se pudo iniciar el juego: {e}": "Couldn't start the game: {e}",
 "Respuesta a la hora: correcta": "Answer about the time: correct",
 "Respuesta a la hora: incorrecta": "Answer about the time: wrong",
 "Respuesta a la hora: sin respuesta": "Answer about the time: no answer",
 "Respuesta a la hora: nunca te la preguntó": "Answer about the time: he never asked you",
 "Récords · finales (<span id=\"historial-cuenta\">0/0</span>)": "Records · endings (<span id=\"historial-cuenta\">0/0</span>)",
 "¡Nuevo récord en {d}!": "New record on {d}!",
 "La una y diez": "Ten past one",
 "El turno no terminó.": "The shift didn't end.",
 "La puerta por fin abrió.": "The door finally opened.",
 "Paseo nocturno": "Night stroll",
 "Un turno sin él, en dificultad Paseo.": "A shift without him, on Stroll difficulty.",
 "Las seis hojas, en la lavadora del claro.": "All six pages, in the washer in the clearing.",
 "La hora verdadera y las seis hojas, la misma noche.": "The true time and all six pages, the same night.",
 "Turnos terminados: {n}": "Shifts finished: {n}",
 "Cada final cuenta, también el de la una y diez.": "Every ending counts, even the one at ten past one.",
 "{d}: {nota}": "{d}: {nota}",
 "{p} puntos · noche {n}": "{p} points · night {n}",
 "{d}: —": "{d}: —",
 "Todavía sin turnos en esta dificultad.": "No shifts on this difficulty yet.",
 "(visto una vez)": "(seen once)",
 "(visto {n} veces)": "(seen {n} times)",
 "Un final oculto.": "A hidden ending.",
 "Fotos (<span id=\"fotos-cuenta\">0</span>)": "Photos (<span id=\"fotos-cuenta\">0</span>)",
 "Saca fotos con <b>P</b>, con <b>Y</b> en el control o desde la pausa. Revísalas bien.": "Take photos with <b>P</b>, with <b>Y</b> on a controller, or from the pause menu. Look at them closely.",
 "Sacar una foto": "Take a photo",
 "P": "P",
 "Sacar una foto con el celular <span class=\"g-nota\">(con flash; revisa bien cada foto)</span>": "Take a photo with your phone <span class=\"g-nota\">(with flash; look closely at every photo)</span>",
 "<span class=\"gesto\">🖐 tres dedos</span> → «Sacar una foto»": "<span class=\"gesto\">🖐 three fingers</span> → “Take a photo”",
 "Sacar una foto con el celular <span class=\"g-nota\">(revisa bien cada foto)</span>": "Take a photo with your phone <span class=\"g-nota\">(look closely at every photo)</span>",
 "Y": "Y",
 "Sacar una foto con el celular": "Take a photo with your phone",
 "Descargar": "Download",
 "Cerrar": "Close",
 "(Revisas la foto. Hay alguien de pie frente a ti. Levantas la vista: no hay nadie.)": "(You check the photo. Someone is standing right in front of you. You look up: no one is there.)",
 "En la foto": "In the picture",
 "Sácale una foto cuando no está.": "Take his picture when he isn't there.",
 "Noche {n} · {h}": "Night {n} · {h}",
 "Compartir": "Share",
 "<span class=\"tecla ancha\">clic</span> en una secadora": "<span class=\"tecla ancha\">click</span> on a dryer",
 "Ponerla a girar con una moneda <span class=\"g-nota\">(junta pelusa en el filtro)</span>": "Start it with a coin <span class=\"g-nota\">(lint builds up in the filter)</span>",
 "<span class=\"gesto\">☝ tocar</span> una secadora": "<span class=\"gesto\">☝ tap</span> a dryer",
 "Corte de agua": "Water shutoff",
 "Cortaron el agua hasta las seis. Las lavadoras no van a arrancar: pon las secadoras o algo de música para tapar el zumbido.": "The water is shut off until six. The washers won't start: run the dryers or put on some music to drown out the hum.",
 "hoy no hay agua. Mete monedas en las secadoras para que giren, o pon tu música: el ruido tapa el zumbido.": "there's no water tonight. Put coins in the dryers to get them spinning, or play your music: the noise drowns out the hum.",
 "Secadoras funcionando: {n} de 4 (hoy no hay agua: con 3 o más, o con tu música, se tapa el zumbido).": "Dryers running: {n} of 4 (no water tonight: with 3 or more, or with your music, the hum is drowned out).",
 "(La perilla gira, pero no entra agua. La lavadora solo zumba.)": "(The knob turns, but no water comes in. The washer just hums.)",
 "(Esta secadora ya está girando.)": "(This dryer is already spinning.)",
 "(Metes una moneda. La secadora arranca con un golpe sordo.)": "(You put in a coin. The dryer starts with a dull thud.)",
 "<span class=\"tecla ancha\">clic</span> en el lavabo": "<span class=\"tecla ancha\">click</span> on the sink",
 "Echarte agua en la cara <span class=\"g-nota\">(baja el miedo; el espejo de arriba… míralo si te atreves)</span>": "Splash water on your face <span class=\"g-nota\">(lowers your fear; the mirror above it… look if you dare)</span>",
 "<span class=\"gesto\">☝ tocar</span> el lavabo": "<span class=\"gesto\">☝ tap</span> the sink",
 "Echarte agua en la cara <span class=\"g-nota\">(baja el miedo)</span>": "Splash water on your face <span class=\"g-nota\">(lowers your fear)</span>",
 "(En el espejo, alguien está de pie detrás de ti. Te das vuelta: no hay nadie.)": "(In the mirror, someone is standing behind you. You turn around: no one is there.)",
 "(En el espejo se ve el pasillo detrás de ti. A ti no.)": "(The mirror shows the corridor behind you. It doesn't show you.)",
 "(El grifo tose aire. Hoy no hay agua.)": "(The tap coughs air. There's no water tonight.)",
 "(Ya tienes la cara empapada.)": "(Your face is already soaked.)",
 "(Te echas agua en la cara. Está helada. Por un momento te sientes despierto.)": "(You splash water on your face. It's ice cold. For a moment you feel awake.)",
 "Dos en el espejo": "Two in the mirror",
 "Míralo detrás de ti en el espejo del pasillo.": "See him behind you in the corridor mirror.",
 "Un espejo de bolsillo": "A pocket mirror",
 "Empañado por dentro, como si alguien hubiera respirado del otro lado.": "Fogged up on the inside, as if someone had breathed on the other side.",
 "Un rollo de fotos sin revelar": "An undeveloped roll of film",
 "Doce exposiciones. En la etiqueta, con tu letra: «no las revelen».": "Twelve exposures. On the label, in your handwriting: “don't develop them”.",
 "Una llave de paso": "A water shutoff key",
 "Fría y mojada. Alguien cerró el agua a propósito.": "Cold and wet. Someone shut off the water on purpose.",
 "Brillo": "Brightness",
 "[Teléfono, con tu propia voz] {l}": "[Phone, in your own voice] {l}",
 "Soy yo otra vez. No lo mires a la cara. Si te pregunta la hora, faltan cinco minutos para las seis. No le digas nada más.": "It's me again. Don't look at his face. If he asks you the time, it's five minutes to six. Don't tell him anything else.",
 "Ya estuviste aquí, ¿verdad? Se te nota en la voz. No lo mires a la cara. Faltan cinco minutos para las seis.": "You've been here before, haven't you? I can hear it in your voice. Don't look at his face. It's five minutes to six.",
 "No te quedes mucho frente al espejo del pasillo. Y si te pregunta la hora: faltan cinco minutos para las seis.": "Don't stand too long in front of the corridor mirror. And if he asks you the time: it's five minutes to six.",
 "Escucha, que se corta... no lo mires... faltan cinco minutos para las seis... las hojas... el claro...": "Listen, it's breaking up... don't look at him... it's five minutes to six... the pages... the clearing...",
 "No lo mires a la cara. Faltan cinco minutos para las seis. Yo tampoco salí, ¿sabes? Sigo aquí, en el turno de antes.": "Don't look at his face. It's five minutes to six. I never got out either, you know. I'm still here, on the shift before yours.",
 "Teléfono público": "Payphone",
 "Noche {n} en adelante": "Night {n} onward",
 "TELÉFONO PÚBLICO · TU PROPIA VOZ · 03:50": "PAYPHONE · YOUR OWN VOICE · 03:50",
 "TELÉFONO PÚBLICO · NOCHE {n} · 03:50": "PAYPHONE · NIGHT {n} · 03:50",
 "Novedades <span id=\"novedades-punto\" class=\"punto-nuevo\" hidden=\"\">● nuevo</span>": "What's new <span id=\"novedades-punto\" class=\"punto-nuevo\" hidden=\"\">● new</span>",
 "El teléfono dice algo distinto cada noche. Desde la sexta, contesta tu propia voz.": "The phone says something different every night. From the sixth on, your own voice answers.",
 "Opción «Brillo», para jugar en el celular con mucha luz.": "“Brightness” option, for playing on your phone in bright light.",
 "El pasillo de servicio tiene un lavabo con espejo. Tú no te reflejas.": "The service corridor has a sink with a mirror. You have no reflection.",
 "Noche especial «Corte de agua»: las secadoras ahora funcionan con moneda.": "Special night “Water shutoff”: the dryers now take coins.",
 "Fotos con la cámara del celular (P, Y o la pausa). Revísalas bien.": "Photos with your phone camera (P, Y or the pause menu). Look at them closely.",
 "A veces la tele muestra algo entre la nieve.": "Sometimes the TV shows something in the static.",
 "Récords: tu mejor nota por dificultad y los cinco finales.": "Records: your best grade per difficulty and the five endings.",
 "English version: Options → Idioma · Language.": "English version: Options → Idioma · Language.",
 "Un final más, para quien hace todo en la misma noche.": "One more ending, for those who do everything in the same night.",
 "Filtro de televisor viejo (CRT) en las opciones.": "Old TV filter (CRT) in the options.",
 "Fondo oscuro detrás de los subtítulos": "Dark background behind subtitles",
 "Opción de fondo oscuro detrás de los subtítulos.": "Option for a dark background behind subtitles.",
 "(Revisas la foto: Pelusa sale movida, como en todas las fotos.)": "(You check the photo: Pelusa came out blurry, like in every photo.)",
 "Álbum de la noche": "Night album",
 "Saca fotos en la lavandería, el bosque y el pasillo en un mismo turno.": "Take photos in the laundromat, the forest, and the corridor in a single shift.",
 "Tormenta eléctrica": "Thunderstorm",
 "Anuncian tormenta eléctrica toda la noche. Si truena cerca, la luz va a parpadear: no te asustes.": "A thunderstorm is forecast all night. If it thunders nearby, the lights will flicker: don't be scared.",
 "Noche especial «Tormenta eléctrica»: relámpagos seguidos y la luz parpadea con los truenos.": "Special night “Thunderstorm”: frequent lightning, and the lights flicker with the thunder.",
 "Logro «Álbum de la noche»: fotos en los tres lugares en un mismo turno.": "“Night album” achievement: photos in all three places in a single shift.",
 "(La moneda está tibia, como si alguien la hubiera tenido en la mano.)": "(The coin is warm, as if someone had been holding it.)",
 "(En la bandeja del cambiador hay una moneda parada de canto. En tu bolsillo falta una.)": "(There's a coin standing on its edge in the change machine tray. One is missing from your pocket.)",
 "Revisa tus monedas. Y la bandeja del cambiador.": "Check your coins. And the change machine tray.",
 "(Alguien dobló ropa que nadie trajo. Huele a tu suavizante.)": "(Someone folded clothes that nobody brought. They smell like your fabric softener.)",
 "(Está tibia, recién salida de una secadora que nadie usó.)": "(They're warm, fresh out of a dryer nobody used.)",
 "A veces alguien dobla ropa en el mostrador. Nadie la trajo.": "Sometimes someone folds clothes on the counter. Nobody brought them.",
 "(Hay huellas mojadas en el piso que van del vidrio al banco amarillo. Son de tu talla.)": "(There are wet footprints on the floor leading from the glass door to the yellow bench. They're your size.)",
 "Antes de irnos: esta va para alguien que sigue doblando ropa ajena a esta hora. Ya sabe quién es.": "Before we go: this one's for someone who's still folding other people's laundry at this hour. They know who they are.",
 "(Entre la estática, alguien dice tu nombre: «…{n}…».)": "(Through the static, someone says your name: “…{n}…”.)",
 "Radio Nocturna tiene una dedicatoria para ti (noches 3 a 6).": "Night Radio has a dedication for you (nights 3 to 6)."
};
